baseURL = 'https://blog.factgear.com/'
languageCode = 'en-us'
title = 'FactGear.com'
theme = "paper"

custom_css = ["css/styles.css"]

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"   

[params]
  # color style
  color = 'light'                           # linen, wheat, gray, light    